FROM node:20

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY ./public/ ./public/
COPY ./src/ ./src/
COPY ./astro.config.mjs tsconfig.json ./

ENV HOST=0.0.0.0
ENV PORT=80

EXPOSE 80

CMD ["npm", "run", "start"]
